logging:
  level:
    root: info
  file:
    name: myapp.log

spring:
#  数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=true
      username: root
      password: 123456
#      热部署
  devtools:
    restart:
      enabled: true
      additional-paths: /src/main/java
  freemarker:
    cache: false
